# Downloading the Dataset

#### This part of the code has been executed only one. I helped me to download the data for each month from 2010 to 2020. I tried different ways to download this dataset but this was the best one even though time consuming. I had the chance to read the menaing of each field and to choose which one to download. At the same time I noticed that the values of the fields were more accurate in this way than downloading the whole dataset at once.

#### We won't need to run this code anymore

Here is the LINK where you can find the meaning of each field in this dataset: https://transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr

In [1]:
import pandas as pd

In [2]:
df_2010_january = pd.read_csv(r'C:/Users/STSC/Downloads/290904056_T_ONTIME_REPORTING/290904056_T_ONTIME_REPORTING.csv')
df_2010_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/january_2010.csv', index = False, header=True)

In [44]:
df_2011_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING/290948635_T_ONTIME_REPORTING.csv')
df_2011_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/january_2011.csv', index = False, header=True)

In [46]:
df_2012_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING/290948635_T_ONTIME_REPORTING.csv')
df_2012_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/january_2012.csv', index = False, header=True)

In [47]:
df_2013_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING/290948635_T_ONTIME_REPORTING.csv')
df_2013_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/january_2013.csv', index = False, header=True)

In [48]:
df_2014_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2014_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/january_2014.csv', index = False, header=True)

In [49]:
df_2015_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2015_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/january_2015.csv', index = False, header=True)

In [50]:
df_2016_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING/290948635_T_ONTIME_REPORTING.csv')
df_2016_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/january_2016.csv', index = False, header=True)

In [51]:
df_2017_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2017_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/january_2017.csv', index = False, header=True)

In [52]:
df_2018_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2018_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/january_2018.csv', index = False, header=True)

In [53]:
df_2019_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2019_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/january_2019.csv', index = False, header=True)

In [54]:
df_2020_january = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2020_january.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_january.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/january_2020.csv', index = False, header=True)

In [56]:
#df_2010_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING/290948635_T_ONTIME_REPORTING.csv')
#df_2010_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
#df_2010_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/february_2010.csv', index = False, header=True)

df_2011_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/february_2011.csv', index = False, header=True)

df_2012_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/february_2012.csv', index = False, header=True)

df_2013_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/february_2013.csv', index = False, header=True)

df_2014_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/february_2014.csv', index = False, header=True)

df_2015_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/february_2015.csv', index = False, header=True)

df_2016_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/february_2016.csv', index = False, header=True)

df_2017_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/february_2017.csv', index = False, header=True)

df_2018_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/february_2018.csv', index = False, header=True)

df_2019_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/february_2019.csv', index = False, header=True)

df_2020_february = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_february.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_february.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/february_2020.csv', index = False, header=True)

In [57]:
df_2011_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/march_2011.csv', index = False, header=True)

df_2012_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/march_2012.csv', index = False, header=True)

df_2013_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/march_2013.csv', index = False, header=True)

df_2014_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/march_2014.csv', index = False, header=True)

df_2015_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/march_2015.csv', index = False, header=True)

df_2016_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/march_2016.csv', index = False, header=True)

df_2017_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/march_2017.csv', index = False, header=True)

df_2018_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/march_2018.csv', index = False, header=True)

df_2019_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/march_2019.csv', index = False, header=True)

df_2020_march = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/march_2020.csv', index = False, header=True)

In [58]:
df_2011_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/april_2011.csv', index = False, header=True)

df_2012_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/april_2012.csv', index = False, header=True)

df_2013_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/april_2013.csv', index = False, header=True)

df_2014_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/april_2014.csv', index = False, header=True)

df_2015_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/april_2015.csv', index = False, header=True)

df_2016_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/april_2016.csv', index = False, header=True)

df_2017_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/april_2017.csv', index = False, header=True)

df_2018_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/april_2018.csv', index = False, header=True)

df_2019_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/april_2019.csv', index = False, header=True)

df_2020_april = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/april_2020.csv', index = False, header=True)

In [59]:
df_2011_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/may_2011.csv', index = False, header=True)

df_2012_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/may_2012.csv', index = False, header=True)

df_2013_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/may_2013.csv', index = False, header=True)

df_2014_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/may_2014.csv', index = False, header=True)

df_2015_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/may_2015.csv', index = False, header=True)

df_2016_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/may_2016.csv', index = False, header=True)

df_2017_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/may_2017.csv', index = False, header=True)

df_2018_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/may_2018.csv', index = False, header=True)

df_2019_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/may_2019.csv', index = False, header=True)

df_2020_may = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/may_2020.csv', index = False, header=True)

In [60]:
df_2011_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/june_2011.csv', index = False, header=True)

df_2012_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/june_2012.csv', index = False, header=True)

df_2013_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/june_2013.csv', index = False, header=True)

df_2014_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/june_2014.csv', index = False, header=True)

df_2015_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/june_2015.csv', index = False, header=True)

df_2016_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/june_2016.csv', index = False, header=True)

df_2017_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/june_2017.csv', index = False, header=True)

df_2018_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/june_2018.csv', index = False, header=True)

df_2019_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/june_2019.csv', index = False, header=True)

df_2020_june = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/june_2020.csv', index = False, header=True)

In [61]:
df_2011_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/july_2011.csv', index = False, header=True)

df_2012_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/july_2012.csv', index = False, header=True)

df_2013_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/july_2013.csv', index = False, header=True)

df_2014_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/july_2014.csv', index = False, header=True)

df_2015_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/july_2015.csv', index = False, header=True)

df_2016_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/july_2016.csv', index = False, header=True)

df_2017_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/july_2017.csv', index = False, header=True)

df_2018_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/july_2018.csv', index = False, header=True)

df_2019_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/july_2019.csv', index = False, header=True)

df_2020_july = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/july_2020.csv', index = False, header=True)

In [62]:
df_2011_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/august_2011.csv', index = False, header=True)

df_2012_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/august_2012.csv', index = False, header=True)

df_2013_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/august_2013.csv', index = False, header=True)

df_2014_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/august_2014.csv', index = False, header=True)

df_2015_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/august_2015.csv', index = False, header=True)

df_2016_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/august_2016.csv', index = False, header=True)

df_2017_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/august_2017.csv', index = False, header=True)

df_2018_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/august_2018.csv', index = False, header=True)

df_2019_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/august_2019.csv', index = False, header=True)

df_2020_august = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/august_2020.csv', index = False, header=True)

In [63]:
df_2011_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/september_2011.csv', index = False, header=True)

df_2012_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/september_2012.csv', index = False, header=True)

df_2013_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/september_2013.csv', index = False, header=True)

df_2014_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/september_2014.csv', index = False, header=True)

df_2015_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/september_2015.csv', index = False, header=True)

df_2016_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/september_2016.csv', index = False, header=True)

df_2017_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/september_2017.csv', index = False, header=True)

df_2018_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/september_2018.csv', index = False, header=True)

df_2019_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/september_2019.csv', index = False, header=True)

df_2020_september = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/september_2020.csv', index = False, header=True)

In [65]:
df_2011_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/october_2011.csv', index = False, header=True)

df_2012_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/october_2012.csv', index = False, header=True)

df_2013_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/october_2013.csv', index = False, header=True)

df_2014_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/october_2014.csv', index = False, header=True)

df_2015_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/october_2015.csv', index = False, header=True)

df_2016_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/october_2016.csv', index = False, header=True)

df_2017_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/october_2017.csv', index = False, header=True)

df_2018_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/october_2018.csv', index = False, header=True)

df_2019_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/october_2019.csv', index = False, header=True)

df_2020_october = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/october_2020.csv', index = False, header=True)

In [66]:
df_2011_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/november_2011.csv', index = False, header=True)

df_2012_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/november_2012.csv', index = False, header=True)

df_2013_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/november_2013.csv', index = False, header=True)

df_2014_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/november_2014.csv', index = False, header=True)

df_2015_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/november_2015.csv', index = False, header=True)

df_2016_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/november_2016.csv', index = False, header=True)

df_2017_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/november_2017.csv', index = False, header=True)

df_2018_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/november_2018.csv', index = False, header=True)

df_2019_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/november_2019.csv', index = False, header=True)

df_2020_november = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/november_2020.csv', index = False, header=True)

In [67]:
df_2011_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (1)/290948635_T_ONTIME_REPORTING.csv')
df_2011_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2011_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2011/december_2011.csv', index = False, header=True)

df_2012_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (2)/290948635_T_ONTIME_REPORTING.csv')
df_2012_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2012_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2012/december_2012.csv', index = False, header=True)

df_2013_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (3)/290948635_T_ONTIME_REPORTING.csv')
df_2013_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2013_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2013/december_2013.csv', index = False, header=True)

df_2014_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (4)/290948635_T_ONTIME_REPORTING.csv')
df_2014_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2014_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2014/december_2014.csv', index = False, header=True)

df_2015_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (5)/290948635_T_ONTIME_REPORTING.csv')
df_2015_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2015_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2015/december_2015.csv', index = False, header=True)

df_2016_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (6)/290948635_T_ONTIME_REPORTING.csv')
df_2016_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2016_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2016/december_2016.csv', index = False, header=True)

df_2017_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (7)/290948635_T_ONTIME_REPORTING.csv')
df_2017_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2017_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2017/december_2017.csv', index = False, header=True)

df_2018_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (8)/290948635_T_ONTIME_REPORTING.csv')
df_2018_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2018_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2018/december_2018.csv', index = False, header=True)

df_2019_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (9)/290948635_T_ONTIME_REPORTING.csv')
df_2019_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2019_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2019/december_2019.csv', index = False, header=True)

df_2020_december = pd.read_csv(r'C:/Users/STSC/Downloads/290948635_T_ONTIME_REPORTING (10)/290948635_T_ONTIME_REPORTING.csv')
df_2020_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2020_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2020/december_2020.csv', index = False, header=True)

In [7]:
df_2010_march = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_march.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_march.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/march_2010.csv', index = False, header=True)

In [8]:
df_2010_april = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_april.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_april.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/april_2010.csv', index = False, header=True)

In [9]:
df_2010_may = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_may.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_may.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/may_2010.csv', index = False, header=True)

In [10]:
df_2010_june = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_june.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_june.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/june_2010.csv', index = False, header=True)

In [11]:
df_2010_july = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_july.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_july.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/july_2010.csv', index = False, header=True)

In [12]:
df_2010_august = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_august.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_august.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/august_2010.csv', index = False, header=True)

In [13]:
df_2010_september = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_september.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_september.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/september_2010.csv', index = False, header=True)

C:\Users\STSC\anaconda3\envs\Tensorflow1\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [14]:
df_2010_october = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_october.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_october.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/october_2010.csv', index = False, header=True)

In [15]:
df_2010_november = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_november.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_november.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/november_2010.csv', index = False, header=True)

In [16]:
df_2010_december = pd.read_csv(r'C:/Users/STSC/Downloads/290915200_T_ONTIME_REPORTING/290915200_T_ONTIME_REPORTING.csv')
df_2010_december.dropna(subset = ["CARRIER_DELAY"], inplace=True)
df_2010_december.to_csv (r'C:/Users/STSC/Desktop/Dataset/2010/december_2010.csv', index = False, header=True)

### Here I have combined the data of each year in one file and at the very end all the years together in one csv file.

In [2]:
import os
import glob

In [19]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2010")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2010_csv.csv", index=False, encoding='utf-8-sig')

In [5]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2011")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2011_csv.csv", index=False, encoding='utf-8-sig')

In [15]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2012")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2012_csv.csv", index=False, encoding='utf-8-sig')

In [9]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2013")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2013_csv.csv", index=False, encoding='utf-8-sig')

In [7]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2014")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2014_csv.csv", index=False, encoding='utf-8-sig')

In [8]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2015")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2015_csv.csv", index=False, encoding='utf-8-sig')

In [10]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2016")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2016_csv.csv", index=False, encoding='utf-8-sig')

In [11]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2017")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2017_csv.csv", index=False, encoding='utf-8-sig')

In [12]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2018")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2018_csv.csv", index=False, encoding='utf-8-sig')

In [13]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2019")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2019_csv.csv", index=False, encoding='utf-8-sig')

In [14]:
os.chdir("C:/Users/STSC/Desktop/Dataset/2020")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_20_csv.csv", index=False, encoding='utf-8-sig')

### This is the final dataset downloaded. You will find it uploaded in the shared Drive folder as well.

In [16]:
os.chdir("C:/Users/STSC/Desktop/Dataset/Combined")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_2010-2020_csv.csv", index=False, encoding='utf-8-sig')

### Load the dataset and create a data frame

In [3]:
import pandas as pd

df_combined = pd.read_csv (r'C:/Users/STSC/Desktop/Dataset/Combined/combined_2010-2020_csv.csv')
print (df_combined)

          YEAR  MONTH  DAY_OF_MONTH OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID  \
0         2010      4            25                9E                  20363
1         2010      4             5                9E                  20363
2         2010      4             6                9E                  20363
3         2010      4             7                9E                  20363
4         2010      4             8                9E                  20363
...        ...    ...           ...               ...                    ...
11221075  2020      9             5                OO                  20304
11221076  2020      9             5                OO                  20304
11221077  2020      9             5                OO                  20304
11221078  2020      9             5                OO                  20304
11221079  2020      9             5                OO                  20304

         OP_CARRIER TAIL_NUM  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID  \
0                9E   86239E               4093              15249
1                9E   85329E               4094              11433
2                9E   80299E               4094              15380
3                9E   89139E               4094              15380
4                9E   86319E               4094              15380
...             ...      ...                ...                ...
11221075         OO   N897SK               3693              13198
11221076         OO   N162PQ               3708              10693
11221077         OO   N162PQ               3708              11433
11221078         OO   N161PQ               3731              13485
11221079         OO   N296SY               3793              11638

          ORIGIN_AIRPORT_SEQ_ID  ...  WEATHER_DELAY NAS_DELAY SECURITY_DELAY  \
0                       1524901  ...            0.0      27.0            0.0
1                       1143301  ...            0.0      24.0            0.0
2                       1538001  ...            0.0       3.0            0.0
3                       1538001  ...            0.0      24.0            0.0
4                       1538001  ...            0.0      24.0            0.0
...                         ...  ...            ...       ...            ...
11221075                1319801  ...            0.0       0.0            0.0
11221076                1069302  ...            0.0       0.0            0.0
11221077                1143302  ...            0.0       0.0            0.0
11221078                1348502  ...            0.0       0.0            0.0
11221079                1163807  ...            0.0       0.0            0.0

         LATE_AIRCRAFT_DELAY DIV_AIRPORT_LANDINGS  DIV_REACHED_DEST  \
0                        0.0                  0.0               NaN
1                        0.0                  0.0               NaN
2                       17.0                  0.0               NaN
3                        0.0                  0.0               NaN
4                        0.0                  0.0               NaN
...                      ...                  ...               ...
11221075                 0.0                  0.0               NaN
11221076                 0.0                  0.0               NaN
11221077                 0.0                  0.0               NaN
11221078                 0.0                  0.0               NaN
11221079                 0.0                  0.0               NaN

          DIV_ACTUAL_ELAPSED_TIME  DIV_ARR_DELAY DIV_DISTANCE Unnamed: 50
0                             NaN            NaN          NaN         NaN
1                             NaN            NaN          NaN         NaN
2                             NaN            NaN          NaN         NaN
3                             NaN            NaN          NaN         NaN
4                             NaN            NaN          NaN         NaN
...                           ...            ...          ...         ...
11221075                      NaN            NaN          NaN         NaN
11221076                      NaN            NaN          NaN         NaN
11221077                      NaN            NaN          NaN         NaN
11221078                      NaN            NaN          NaN         NaN
11221079                      NaN            NaN          NaN         NaN

[11221080 rows x 51 columns]

### Remove some colomns that I already know we won't need

In [4]:
new_df = df_combined.drop(['DIV_REACHED_DEST', 'DIV_ACTUAL_ELAPSED_TIME', 'TAIL_NUM', 'OP_CARRIER_FL_NUM',  'DIV_ARR_DELAY', 'DIV_DISTANCE'], axis = 1)

### Import some libraries that I will need later on for data cleaning and some simple analysis of the dataset

In [5]:
import datetime, warnings, scipy 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import ConnectionPatch
from collections import OrderedDict
from matplotlib.gridspec import GridSpec

from sklearn import metrics, linear_model
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from scipy.optimize import curve_fit
plt.rcParams["patch.force_edgecolor"] = True
plt.style.use('fivethirtyeight')
mpl.rc('patch', edgecolor = 'dimgray', linewidth=1)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last_expr"
pd.options.display.max_columns = 50
%matplotlib inline
warnings.filterwarnings("ignore")

#### gives some infos on columns types and number of null values

In [6]:

tab_info=pd.DataFrame(new_df.dtypes).T.rename(index={0:'column type'})
tab_info=tab_info.append(pd.DataFrame(new_df.isnull().sum()).T.rename(index={0:'null values (nb)'}))
tab_info=tab_info.append(pd.DataFrame(new_df.isnull().sum()/new_df.shape[0]*100)
                         .T.rename(index={0:'null values (%)'}))
tab_info

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DIV_AIRPORT_LANDINGS,Unnamed: 50
column type,int64,int64,int64,object,int64,object,int64,int64,int64,object,object,object,object,int64,int64,int64,object,object,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
null values (nb),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2,1,301,301,301,3,1,1,1,1,1,11221080,1,3,1,1,1,1,1,1,1,1,1,1,11221080
null values (%),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000009,0.000009,0.000009,0.000018,0.000009,0.002682,0.002682,0.002682,0.000027,0.000009,0.000009,0.000009,0.000009,0.000009,100.0,0.000009,0.000027,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,0.000009,100.0

#### The date column is splitet in three. We will need a single column for the full date in datetime format. This is what I am doing below.

In [7]:
new_df['DAY'] = new_df['DAY_OF_MONTH'] 
new_df['DAY'] = new_df.loc[:, 'DAY_OF_MONTH']

In [8]:
new_df.head()

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DIV_AIRPORT_LANDINGS,Unnamed: 50,DAY
0,2010,4,25,9E,20363,9E,15249,1524901,35249,TLH,"Tallahassee, FL",FL,Florida,13244,1324401,33244,MEM,"Memphis, TN",TN,Tennessee,1220.0,1228.0,8.0,8.0,0.0,1256.0,1331.0,35.0,35.0,1.0,0.0,NaN,0.0,96.0,123.0,78.0,1.0,458.0,8.0,0.0,27.0,0.0,0.0,0.0,NaN,25
1,2010,4,5,9E,20363,9E,11433,1143301,31295,DTW,"Detroit, MI",MI,Michigan,12945,1294502,32945,LEX,"Lexington, KY",KY,Kentucky,1935.0,1934.0,-1.0,0.0,0.0,2056.0,2120.0,24.0,24.0,1.0,0.0,NaN,0.0,81.0,106.0,74.0,1.0,296.0,0.0,0.0,24.0,0.0,0.0,0.0,NaN,5
2,2010,4,6,9E,20363,9E,15380,1538001,35380,TVC,"Traverse City, MI",MI,Michigan,11433,1143301,31295,DTW,"Detroit, MI",MI,Michigan,1720.0,1737.0,17.0,17.0,1.0,1825.0,1845.0,20.0,20.0,1.0,0.0,NaN,0.0,65.0,68.0,43.0,1.0,207.0,0.0,0.0,3.0,0.0,17.0,0.0,NaN,6
3,2010,4,7,9E,20363,9E,15380,1538001,35380,TVC,"Traverse City, MI",MI,Michigan,11433,1143301,31295,DTW,"Detroit, MI",MI,Michigan,1720.0,1721.0,1.0,1.0,0.0,1825.0,1849.0,24.0,24.0,1.0,0.0,NaN,0.0,65.0,88.0,41.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,0.0,NaN,7
4,2010,4,8,9E,20363,9E,15380,1538001,35380,TVC,"Traverse City, MI",MI,Michigan,11433,1143301,31295,DTW,"Detroit, MI",MI,Michigan,1720.0,1709.0,-11.0,0.0,0.0,1825.0,1849.0,24.0,24.0,1.0,0.0,NaN,0.0,65.0,100.0,47.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,0.0,NaN,8

In [9]:
new_df = new_df.drop(['DAY_OF_MONTH'], axis = 1)

In [10]:
new_df['DATE'] = pd.to_datetime(new_df[['YEAR','MONTH', 'DAY']])

In [11]:
#_________________________________________________________
# Function that convert the 'HHMM' string to datetime.time
def format_heure(chaine):
    if pd.isnull(chaine):
        return np.nan
    else:
        if chaine == 2400: chaine = 0
        chaine = "{0:04d}".format(int(chaine))
        heure = datetime.time(int(chaine[0:2]), int(chaine[2:4]))
        return heure
#_____________________________________________________________________
# Function that combines a date and time to produce a datetime.datetime
def combine_date_heure(x):
    if pd.isnull(x[0]) or pd.isnull(x[1]):
        return np.nan
    else:
        return datetime.datetime.combine(x[0],x[1])
#_______________________________________________________________________________
# Function that combine two columns of the dataframe to create a datetime format
def create_flight_time(df, col):    
    liste = []
    for index, cols in new_df[['DATE', col]].iterrows():    
        if pd.isnull(cols[1]):
            liste.append(np.nan)
        elif float(cols[1]) == 2400:
            cols[0] += datetime.timedelta(days=1)
            cols[1] = datetime.time(0,0)
            liste.append(combine_date_heure(cols))
        else:
            cols[1] = format_heure(cols[1])
            liste.append(combine_date_heure(cols))
    return pd.Series(liste)

In [12]:
# and I call them to modify the dataframe variables:

new_df['CRS_DEP_TIME'] = create_flight_time(new_df, 'CRS_DEP_TIME')
new_df['DEP_TIME'] = new_df['DEP_TIME'].apply(format_heure)
new_df['CRS_ARR_TIME'] = new_df['CRS_ARR_TIME'].apply(format_heure)
new_df['ARR_TIME'] = new_df['ARR_TIME'].apply(format_heure)
#__________________________________________________________________________
new_df.loc[:5, ['CRS_DEP_TIME', 'CRS_ARR_TIME', 'DEP_TIME',
             'ARR_TIME', 'DEP_DELAY', 'ARR_DELAY']]

         CRS_DEP_TIME CRS_ARR_TIME  DEP_TIME  ARR_TIME  DEP_DELAY  ARR_DELAY
0 2010-04-25 12:20:00     12:56:00  12:28:00  13:31:00        8.0       35.0
1 2010-04-05 19:35:00     20:56:00  19:34:00  21:20:00       -1.0       24.0
2 2010-04-06 17:20:00     18:25:00  17:37:00  18:45:00       17.0       20.0
3 2010-04-07 17:20:00     18:25:00  17:21:00  18:49:00        1.0       24.0
4 2010-04-08 17:20:00     18:25:00  17:09:00  18:49:00      -11.0       24.0
5 2010-04-09 17:20:00     18:25:00  19:09:00  20:04:00      109.0       99.0

The content of the DEP_TIME and ARR_TIME variables can be a bit misleading since they don't contain the dates. For exemple, in the first entry of the dataframe, the scheduled departure is at 0h05 the 1st of January. The DEP_TIME variable indicates 23h54 and we thus don't know if the flight left early or if there was a large delay. Hence, the DEP_DELAY and ARR_DELAY variables proves more useful since they directly provides the delays in minutes. Hence, in what follows, I will not use the DEP_TIME and ARR_TIME variables.

In [13]:
#variables_to_remove = ['OP_CARRIER', 'OP_CARRIER_AIRLINE_ID','ORIGIN', 'ORIGIN_CITY_MARKET_ID', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_NM','DEST_AIRPORT_ID' 'DEST_CITY_MARKET_ID', 'DEST_AIRPORT_SEQ_ID', 'DEST_STATE_ABR', 'DEST','ARR_DELAY_NEW', 'DEST_STATE_NM','DAY', 'YEAR', 'MONTH','AIR_TIME', 'ACTUAL_ELAPSED_TIME', 'ARR_DELAY_NEW', 'Unnamed: 50', 'CANCELLATION_CODE']
new_df = new_df.drop(['OP_CARRIER', 'OP_CARRIER_AIRLINE_ID','ORIGIN', 'ORIGIN_CITY_MARKET_ID', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_NM','DEST_AIRPORT_ID', 'DEST_CITY_MARKET_ID', 'DEST_AIRPORT_SEQ_ID', 'DEST_STATE_ABR', 'DEST','ARR_DELAY_NEW', 'DEST_STATE_NM','DAY', 'YEAR', 'MONTH','AIR_TIME', 'ACTUAL_ELAPSED_TIME', 'ARR_DELAY_NEW', 'Unnamed: 50', 'CANCELLATION_CODE'], axis = 1)

In [14]:
new_df.head()

,OP_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_NAME,DEST_CITY_NAME,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DEL15,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DIV_AIRPORT_LANDINGS,DATE
0,9E,15249,1524901,"Tallahassee, FL","Memphis, TN",2010-04-25 12:20:00,12:28:00,8.0,8.0,0.0,12:56:00,13:31:00,35.0,1.0,0.0,0.0,96.0,1.0,458.0,8.0,0.0,27.0,0.0,0.0,0.0,2010-04-25
1,9E,11433,1143301,"Detroit, MI","Lexington, KY",2010-04-05 19:35:00,19:34:00,-1.0,0.0,0.0,20:56:00,21:20:00,24.0,1.0,0.0,0.0,81.0,1.0,296.0,0.0,0.0,24.0,0.0,0.0,0.0,2010-04-05
2,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-06 17:20:00,17:37:00,17.0,17.0,1.0,18:25:00,18:45:00,20.0,1.0,0.0,0.0,65.0,1.0,207.0,0.0,0.0,3.0,0.0,17.0,0.0,2010-04-06
3,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-07 17:20:00,17:21:00,1.0,1.0,0.0,18:25:00,18:49:00,24.0,1.0,0.0,0.0,65.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,0.0,2010-04-07
4,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-08 17:20:00,17:09:00,-11.0,0.0,0.0,18:25:00,18:49:00,24.0,1.0,0.0,0.0,65.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,0.0,2010-04-08

In [17]:
new_df = new_df.drop(['CANCELLED', 'DIVERTED', 'CRS_ELAPSED_TIME', 'FLIGHTS', 'DIV_AIRPORT_LANDINGS'], axis = 1)

In [18]:
new_df.head()

,OP_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_NAME,DEST_CITY_NAME,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DEL15,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DATE
0,9E,15249,1524901,"Tallahassee, FL","Memphis, TN",2010-04-25 12:20:00,12:28:00,8.0,8.0,0.0,12:56:00,13:31:00,35.0,1.0,458.0,8.0,0.0,27.0,0.0,0.0,2010-04-25
1,9E,11433,1143301,"Detroit, MI","Lexington, KY",2010-04-05 19:35:00,19:34:00,-1.0,0.0,0.0,20:56:00,21:20:00,24.0,1.0,296.0,0.0,0.0,24.0,0.0,0.0,2010-04-05
2,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-06 17:20:00,17:37:00,17.0,17.0,1.0,18:25:00,18:45:00,20.0,1.0,207.0,0.0,0.0,3.0,0.0,17.0,2010-04-06
3,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-07 17:20:00,17:21:00,1.0,1.0,0.0,18:25:00,18:49:00,24.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,2010-04-07
4,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-08 17:20:00,17:09:00,-11.0,0.0,0.0,18:25:00,18:49:00,24.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,2010-04-08

In [20]:
new_df.head()

,OP_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_NAME,DEST_CITY_NAME,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DEL15,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DATE
0,9E,15249,1524901,"Tallahassee, FL","Memphis, TN",2010-04-25 12:20:00,12:28:00,8.0,8.0,0.0,12:56:00,13:31:00,35.0,1.0,458.0,8.0,0.0,27.0,0.0,0.0,2010-04-25
1,9E,11433,1143301,"Detroit, MI","Lexington, KY",2010-04-05 19:35:00,19:34:00,-1.0,0.0,0.0,20:56:00,21:20:00,24.0,1.0,296.0,0.0,0.0,24.0,0.0,0.0,2010-04-05
2,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-06 17:20:00,17:37:00,17.0,17.0,1.0,18:25:00,18:45:00,20.0,1.0,207.0,0.0,0.0,3.0,0.0,17.0,2010-04-06
3,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-07 17:20:00,17:21:00,1.0,1.0,0.0,18:25:00,18:49:00,24.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,2010-04-07
4,9E,15380,1538001,"Traverse City, MI","Detroit, MI",2010-04-08 17:20:00,17:09:00,-11.0,0.0,0.0,18:25:00,18:49:00,24.0,1.0,207.0,0.0,0.0,24.0,0.0,0.0,2010-04-08

In [21]:
new_df.to_csv (r'C:/Users/STSC/Desktop/Dataset/Cleaned_Dataset.csv', index = False, header=True)

In [22]:
new_df.shape

(11221080, 21)